### PR TITLE
Add some Pete Seeger

### PR DESCRIPTION
**Pull request by davatron5000**

### CODE REVIEW

**Comment by charliewilco** [comment]
@davatron5000 anything in particular? not much of dust bowl guy.

**Comment by davatron5000** [comment]
@charlespeters oh. sorry, this is a PR. I added a couple of quotes. I probably need to bump the version number too huh?

**Comment by charliewilco** [comment]
crap, i've been up all night, i thought i was an issue LMAO

**Comment by charliewilco** [comment]
will republish to npm in a minute or two.

**Pull request merged**
